[package]
name = "server"
version = "0.1.0"
edition = "2021"

[dependencies]
core = { path = "../core" }
database = { path = "../database" }
axum = "0.6.20"
log = { version = "0.4.20", features = ["release_max_level_error"] }
tokio = { version = "1.32.0", features = ["full"] }
tower-http = { version = "0.4.3", features = ["fs"] }
serde = { version = "1.0.187", features = ["derive"] }
chrono= "0.4.26"
itertools = "0.10.5"
