[package]
name = "server"
version = "0.1.0"
edition = "2021"

[dependencies]
core = { path = "../core" }
database = { path = "../database" }
axum = "0.7.4"
log = { version = "0.4.20", features = ["release_max_level_error"] }
tokio = { version = "1.35.1", features = ["full"] }
tower-http = { version = "0.5.1", features = ["fs"] }
serde = { version = "1.0.196", features = ["derive"] }
chrono= "0.4.33"
itertools = "0.12.0"
