[package]
name = "server"
version = "0.1.0"
edition = "2021"

[dependencies]
core = { path = "../core" }
database = { path = "../database" }
axum = "0.6.18"
log = { version = "0.4.17", features = ["release_max_level_error"] }
tokio = { version = "1.28.1", features = ["full"] }
tower-http = { version = "0.4.0", features = ["fs"] }
serde = { version = "1.0.162", features = ["derive"] }
chrono= "0.4.24"
itertools = "0.10.5"
