kind: pipeline
name: default

steps: 
  - name: build
    image: docker:latest
    depends_on: [ clone ]
    volumes:
      - name: docker_sock
        path: /var/run/docker.sock
    commands:
      - docker build -t football-simulator:1.0.0.$$DRONE_BUILD_NUMBER -f "build/Football.Dockerfile" .
    when:
      branch:
        - master
      event:
        exclude:
          - pull_request

  - name: clear
    image: docker:dind
    depends_on: [ build ]
    privileged: true
    failure: ignore
    volumes:
      - name: docker_sock
        path: /var/run/docker.sock
    commands:
      - docker stop football-simulator || true
      - docker rm football-simulator || true
    when:
      branch:
        - master

  - name: deploy
    image: docker:dind
    depends_on: [ clear ]
    privileged: true
    failure: ignore
    volumes:
      - name: docker_sock
        path: /var/run/docker.sock
    commands:
      - docker run -d -p 172.17.0.1:18000:18000 --restart always --name football-simulator football-simulator:1.0.0.$$DRONE_BUILD_NUMBER
    when:
      branch:
        - master
      event:
        exclude:
          - pull_request

volumes:
  - name: docker_sock
    host:
      path: /var/run/docker.sock