[package]
name = "football_simulator"
version = "0.1.0"
authors = ["ZOXEXIVO <zoxexivo@gmail.com>"]
edition = "2018"

[dependencies]
core = { path = "src/core" }
actix-web = "4.1.0"
askama = "0.11.1"
actix-files = "0.6.1"
serde_json = "1.0.81"
serde = "1.0.137"
parking_lot = "0.12.1"
log = { version = "0.4.17", features = ["release_max_level_error"] }
env_logger = "0.9.0"
itertools = "0.10.3"
chrono = "0.4.19"
color-eyre = "0.6.1"
