[package]
name = "football_simulator"
version = "0.1.0"
authors = ["ZOXEXIVO <zoxexivo@gmail.com>"]
edition = "2018"

[dependencies]
core = { path = "src/core" }
server = { path = "src/server" }
database = { path = "src/database" }
serde_json = "1.0.105"
serde = "1.0.188"
log = { version = "0.4.20", features = ["release_max_level_error"] }
env_logger = "0.10.0"
itertools = "0.10.5"
chrono = "0.4.30"
color-eyre = "0.6.2"
tokio = { version = "1.32.0", features = ["full"] }
rand = "0.8.5"
