[package]
name = "football_simulator"
version = "0.1.0"
authors = ["ZOXEXIVO <zoxexivo@gmail.com>"]
edition = "2018"

[dependencies]
core = { path = "src/core" }
actix-web = "3.3.3"
askama = "0.11.0"
actix-files = "0.5.0"
serde_json = "1.0.73"
serde = "1.0.132"
parking_lot = "0.11.2"
log = { version = "0.4.14", features = ["release_max_level_error"] }
env_logger = "0.9.0"
itertools = "0.10.3"
chrono = "0.4.19"
color-eyre = "0.5.11"
