[package]
name = "core"
version = "0.1.0"
authors = ["ZOXEXIVO <zoxexivo@gmail.com>"]
edition = "2021"

[dependencies]
chrono = "0.4.37"
rand = "0.8.5"
rayon = "1.10.0"
rand_distr = "0.4.3"
serde = { version = "1.0.197", features = ["derive"] }
serde_json = "1.0.115"
log = { version = "0.4.21", features = ["release_max_level_debug"] }
itertools = "0.12.1"
lazy_static = "1.4.0"
nalgebra = "0.32.5"
