[package]
name = "core"
version = "0.1.0"
authors = ["ZOXEXIVO <zoxexivo@gmail.com>"]
edition = "2021"

[dependencies]
chrono = "0.4.31"
rand = "0.8.5"
rayon = "1.8.0"
rand_distr = "0.4.3"
serde = { version = "1.0.195", features = ["derive"] }
serde_json = "1.0.111"
log = { version = "0.4.20", features = ["release_max_level_debug"] }
itertools = "0.12.0"
lazy_static = "1.4.0"
nalgebra = "0.32.3"
