[package]
name = "core"
version = "0.1.0"
authors = ["ZOXEXIVO <zoxexivo@gmail.com>"]
edition = "2021"

[dependencies]
chrono = "0.4.23"
rand = "0.8.5"
rayon = "1.6.0"
rand_distr = "0.4.3"
serde = "1.0.148"
serde_json = "1.0.89"
log = { version = "0.4.17", features = ["release_max_level_debug"] }
itertools = "0.10.5"
