[package]
name = "core"
version = "0.1.0"
authors = ["ZOXEXIVO <zoxexivo@gmail.com>"]
edition = "2021"

[dependencies]
chrono = "0.4.19"
rand = "0.8.4"
rayon = "1.5.1"
rand_distr = "0.4.2"
serde = "1.0.130"
serde_json = "1.0.72"
log = { version = "0.4.14", features = ["release_max_level_debug"] }
itertools = "0.10.1"
