[package]
name = "core"
version = "0.1.0"
authors = ["ZOXEXIVO <zoxexivo@gmail.com>"]
edition = "2021"

[dependencies]
chrono = "0.4.38"
rand = "0.8.5"
rayon = "1.10.0"
rand_distr = "0.4.3"
serde = { version = "1.0.204", features = ["derive"] }
serde_json = "1.0.120"
log = { version = "0.4.22", features = ["release_max_level_debug"] }
itertools = "0.13.0"
lazy_static = "1.5.0"
nalgebra = "0.33.0"
