[package]
name = "core"
version = "1.0.0"
authors = ["ZOXEXIVO <zoxexivo@gmail.com>"]
edition = "2021"

[dependencies]
chrono = "0.4.39"
rand = "0.8.5"
rayon = "1.10.0"
serde = { version = "1.0.217", features = ["derive"] }
log = "0.4.24"
itertools = "0.14.0"
nalgebra = { version = "0.33.2", features = ["serde-serialize", "rand"] }
burn = { version = "0.15", features = ["ndarray"] }