[package]
name = "dev_graphics"
version = "0.1.0"
edition = "2021"

[dependencies]
macroquad = "0.4.5"
core = { path = "../../core" }
rand = "0.8.5"
rayon = "1.10.0"
serde = { version = "1.0.197", features = ["derive"] }
serde_json = "1.0.114"
