[package]
name = "dev_graphics"
version = "0.1.0"
edition = "2021"

[dependencies]
macroquad = "0.4"
core = { path = "../../core" }
rand = "0.8.5"
rayon = "1.8.1"
serde = { version = "1.0.196", features=["derive"] }
serde_json = "1.0.112"
