[package]
name = "dev_neural_network"
version = "0.1.0"
edition = "2021"

[dependencies]
core = { path = "../../core" }
rand = "0.8.5"
rayon = "1.10.0"
serde = { version = "1.0.217", features = ["derive"] }
serde_json = "1.0.134"
nalgebra = { version = "0.33.2", features = ["serde-serialize"] }